services:
  jaeger:
    image: jaegertracing/jaeger:2.0.0
    user: "root"
    command: ["--config", "/etc/jaeger/config.yaml"]
    ports:
      - "16686:16686"
    volumes:
      - ./deployment/jaeger/config.yaml:/etc/jaeger/config.yaml
      - jaeger-data:/data

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./deployment/otel-collector/config.yaml:/etc/otel-collector.yaml
    ports:
      - "4318:4318"
    depends_on:
      - jaeger

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./deployment/grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    depends_on:
      - jaeger

volumes:
  grafana-storage:
  jaeger-data:
