services:
  jaeger:
    image: jaegertracing/jaeger:2.0.0
    user: "root"
    command: ["--config", "/etc/jaeger/config.yaml"]
    ports:
      - "16686:16686"
    volumes:
      - ./jaeger/config.yaml:/etc/jaeger/config.yaml
      - jaeger-data:/data

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector/config.yaml:/etc/otel-collector.yaml
    ports:
      - "4318:4318"
      - "8889:8889"
    depends_on:
      - jaeger
      - prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    depends_on:
      - jaeger
      - prometheus

volumes:
  grafana-storage:
  jaeger-data:
  prometheus-data:
